artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/imdb


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "unsupervised", "dataset_dict.json"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/imdb
  tokenizer_name: bert-base-uncased


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/imdb
  model_name: bert-base-uncased


predict:
  model_path: artifacts/model_trainer
  tokenizer_path: artifacts/model_trainer